// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vslmddsbmznplivthcnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzbG1kZHNibXpucGxpdnRoY25qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTY3MTUsImV4cCI6MjA2ODQ5MjcxNX0.2GM39pQkmG4CZwNFdF_TJSJj5CJrhQWE-X8gGnW3ALI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});